### ISSUE TITLE
Agregar información principal para básico .css, y .html

### ISSUE THREAD

**Issue by FabiolaYon** [FabiolaYon/Practica2_Fabiola#10]
Insertamos código principal para la práctica
Creamos HTML con la opción de input y onclick
Añadimos estilo en style.css

**Comment by lattaai13** [comment]
Hello, I tried to solve the issue.

This is what I did:

Added an input field and a button with an onclick event to the HTML file. Updated the CSS to style the new elements and maintain consistency with the existing design.

You can review changes in this commit: https://github.com/lattaai13/FabiolaYon-Practica2_Fabiola-10/commit/bc3c226f1e8520f1f3170a397298386626011db2.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
